Bedingte Sprungbefehle:
컴컴컴컴컴컴컴컴컴컴컴
(vr=vorzeichenrichtig)

Sprung, wenn:

JA   /JNBE   - groesser

JAE  /JNB    - groesser/gleich

JB   /JNAE   - kleiner

JBE  /JNA    - kleiner/gleich

JC           -  Carryflag gesetzt

JCXZ /JECXZ  -  (E)CX=0

JE   /JZ     -  gleich (ZF=1)

JG   /JNLE   -  vr. groesser

JGE  /JNL    -  vr. groesser/gleich

JL   /JNGE   -  vr. kleiner

JLE  /JNG    -  vr. kleiner/gleich

JNC          -  Carryflag nicht gesetzt

JNE  /JNZ    -  nicht gleich (ZF=0)

JNO          -  kein Ueberlauf (OF=0)

JNP  /JPO    -  Parity-Flag nicht gesetzt

JNS          -  positiv/Vorzeichen nicht gesetzt

JO           -  Ueberlauf

JP   /JPE    -  Parity-Flag gesetzt

JS           -  negativ/Vorzeichen gesetzt